### ISSUE TITLE
Method to force more RP / communication.

### ISSUE THREAD

**Issue by Shephoris** [WW2-SS13/WW13#158]
Add a 5 minute delay to respawning once ghosted.  Only allow ghosting once someone is actually dead so that they can RP their dying moment. This will hopefully force people to RP more, and work together more. I feel that death isn't feared at all, because you can ghost whilst in pain crit, and respawn straight off.  It's also affecting the quantity of RP.  It would be good to begin to see more people crying out for their mothers, or RP'ing agony whilst slowly dying.

**Comment by subdon** [comment]
adding a 5 minute delay is alright and will help but will not tackle the main issue:
Will not force RP
I feel the "do not fear death" status of the soldiers might be becuse you can literally die at any moment due to bullet mechanics as they are
you can be killed by a stray bullet without proper gauze, you can die at any moment from cover since most bullets cut it through, you can die by full cover, resting , near trees
why not try and rush to the enemy instead if i am going to die anyways? <---kind of suicide mentatlity
I would suggest if attempting to tackle this issue to look at bullet mechanics and buff covers in general

**Comment by Steelpoint** [comment]
The five minute delay is a good idea but it also needs to be paired with a re-examination of the medical system.

Death comes very easily in NML, a single rifle bullet, hell even shrapnel, could rupture your internal organs and spell our a guaranteed death even with prompt medical assistance.

This helps create a atmosphere of devaluing a individual life.

**Comment by chesse20** [comment]
dowm vote to this one i love the rambo gameplay as is right now

**Comment by tylerh95** [comment]
Idea is encompassed in #178
