### ISSUE TITLE
Allowing female characters to play certain roles on german side

### ISSUE THREAD

**Issue by MasterJJ99** [WW2-SS13/WW13#200]
Currently Heer forces you to be Male. German women were historically allowed to serve the wehrmacht as telegraph and radio operators and as defense personnel. Also they served as nurses and doctors in the red-cross. This should be added in the game. Suggestion is to remove the ooc restriction on gender. add more non combat roles

**Comment by Wesreidau** [comment]
The Red Army is full of women for the snowflake factor. Allowing women in the Heer team will bring a lot more work on the moderators as people show up as women Soldats. Women were allowed as rear-area personnel only, with National Socialism making absolutely no concessions to feminism unlike Communism's hypocritical equality-except-in-practice. I have been in favor of women as nurses in the Heer, but I've lost an interest in pushing for this since I keep seeing the base doctors running off to the front.

**Comment by MasterJJ99** [comment]
It even could just be a white list for nurses and they need to stay at base at all times

**Comment by chesse20** [comment]
juz let ppl play female characters whenever

**Comment by Harcourt1** [comment]
In 1945, there numbered 500,000 women auxiliaries in the Wehrmacht (Wehrmachtshelferinnen), who were at the heart of the Heer, the Luftwaffe and the Kriegsmarine. About half of them were volunteers, the others performing obligatory service connected to the war effort (Kriegshilfsdienst). They took part, under the same authority as prisoners of war (Hiwis), as auxiliary personnel of the army (Behelfspersonal) and they were assigned to duties not only within the heart of the Reich, but to a lesser extent, to the occupied territories, for example in the General government of occupied Poland, in France, and later in Yugoslavia, in Greece and in Romania.

They essentially participated :

as telephone, telegraph and transmission operators,
as administrative clerks typists and messengers,
in anti-aircraft defense, as operators of listening equipment, operating projectors for anti-aircraft defense, employees within meteorology services, and auxiliary civil defense personnel
in military health service, as volunteer nurses with the German Red Cross or other voluntary organizations

**Comment by Harcourt1** [comment]
Closing issue. You area allowed to play female but you must justify it ICly. Final say.
