### ISSUE TITLE
Shell casing clean up

### ISSUE THREAD

**Issue by Bubblecum** [WW2-SS13/WW13#88]
Should be an admin method of insta cleaning all shells for better server performance

**Comment by Bernhaben** [comment]
Well, if they get removed... The immersion will be bogged down quiet a bit.

**Comment by Soundwavesghost** [comment]
Likely a built in timer to clear bullets, gameplay on this one becomes a issue when three maxims,  30 Soldats and six machine-gunners unload all their shells, and each little shell gets the same processing time as a person does. Its annoying enough when it bogs down due to high pop but low pop being equally laggy just because of shell processing is something we could avoid.

**Comment by Wesreidau** [comment]
Every X minutes, delete half the shells?

**Comment by Bubblecum** [comment]
Immersion is great and all but when it gets to the point where it becomes a turn based shooter, you're gonna have a problem

**Comment by Alexshreds** [comment]
Alternatively you can process this so a pile of 10+ individual shells is deleted and replaced with a single simple object representing a pile of shells.
